apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: task-manager

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: vishakha12345/task-manager-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            - name: MONGO_URI
              value: mongodb://mongodb:27017/task-manager