apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: task-manager

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: vishakha12345/task-manager-frontend:latest

          ports:
            - containerPort: 80